### ISSUE TITLE
Empty output from a tool

### ISSUE THREAD

**Issue by FixRM** [odinserj/stdump#4]
Hello, @odinserj. I'm trying to collect logs from sample Hangfire, app but I got empty result. I tried to run my app in a console and as Windows service but no luck. I manually download last release from here. I'm running .Framework 4.7.1 on latest Windows 11. What am I doing wrong?

I put my app here: https://github.com/FixRM/Hangfirelogs/tree/main/HangfireDemo. We finally find a way to reproduce issue with leakage of worker threads that I reported earlier.

**Comment by FixRM** [comment]
We got a dump on another machine: https://github.com/FixRM/Hangfirelogs/blob/main/stdump_demo.txt. Should I open at issue in HF repo, or we can continue here? I can see that threads #27 and #28 are running a job, but UI show only one:

![image](https://github.com/HangfireIO/stdump/assets/29232166/10c2d1d7-da25-436a-bde3-92e268060916)

Is it storage, or UI or whatever issue?

**Comment by odinserj** [comment]
Can you show me all the state transitions of that active processing job? It is theoretically possible that it gets executed by multiple workers inside the same Hangfire Server, if storage implementation allows this, and I'd like to understand whether it's the case.

**Comment by FixRM** [comment]
Sure @odinserj, how can I do that? There was only one server in experiment, state transitions are not customized. Hangfire setup was basic: only storage + `wokercount` was set to two.

**Comment by odinserj** [comment]
Just wanted to check screenshot like the following one to see how many "Processing" entries it contains.

![image](https://github.com/HangfireIO/stdump/assets/1078718/61ddc573-7653-4323-a558-b93a0b15546f)

**Comment by FixRM** [comment]
Here it is

![image](https://github.com/HangfireIO/stdump/assets/29232166/eaa652b8-3e3b-40d7-8dcb-f5dbc9a4a381)

**Comment by odinserj** [comment]
Thanks, so my assumption was correct. Can you please include the full screenshot to understand the timings, e.g. when second transition to the Processing state was performed?

**Comment by FixRM** [comment]
I guess this one was queued last week. If you want I can clear DB and start experiment from scratch

![image](https://github.com/HangfireIO/stdump/assets/29232166/25ec9fd8-5576-4fdc-8b23-005d7fc0df97)

**Comment by FixRM** [comment]
Hello @odinserj. Sorry for asking, what are our next steps?

**Comment by odinserj** [comment]
Sorry for the delayed response. For some reason, another worker from the same process is picking up a job, despite previous one is still running. Perhaps something is incorrect in the fault detection logic of the storage implementation, since it allows a background job to be fetched again when there was no any failure. Last week I started an infinite job using the Hangfire.Pro.Redis, here's the output so it's still running:

![image](https://github.com/HangfireIO/stdump/assets/1078718/6f016caa-fe9a-4ec7-a289-c3dd1e88aa45)

I see you are using Hangfire.Redis.StackExchange, a community-based implementation of Redis as a job storage. Please try raising an issue in their repository instead, with all of these screenshots.

**Comment by FixRM** [comment]
Thanks a lot!

**Comment by odinserj** [comment]
Not at all, Artem
